CREATE TABLE "Addresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ZipCode" text NOT NULL,
    "Street" text NOT NULL,
    "Number" text NOT NULL,
    "Complement" text,
    "Neighborhood" text NOT NULL,
    "City" text NOT NULL,
    "State" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);


CREATE TABLE "PaymentMethods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(60) NOT NULL,
    "Code" character varying(30) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id")
);


CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(100) NOT NULL,
    "Module" character varying(50) NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);


CREATE TABLE "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(250) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "CostPrice" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "EstimatedTimeMinutes" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);


CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "CpfCnpj" character varying(20),
    "Phone" character varying(20),
    "CellPhone" character varying(20),
    "Email" character varying(100),
    "BirthDate" timestamp without time zone,
    "Notes" text,
    "IsActive" boolean NOT NULL,
    "AddressId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customers_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL
);


CREATE TABLE "Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CorporateName" character varying(150) NOT NULL,
    "TradeName" character varying(150) NOT NULL,
    "CpfCnpj" character varying(20),
    "StateRegistration" text,
    "Phone" text,
    "CellPhone" text,
    "Email" text,
    "Notes" text,
    "IsActive" boolean NOT NULL,
    "AddressId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Suppliers_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL
);


CREATE TABLE "WorkshopSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyName" character varying(150) NOT NULL,
    "TradeName" character varying(150) NOT NULL,
    "CorporateName" character varying(150) NOT NULL,
    "CpfCnpj" character varying(20),
    "StateRegistration" character varying(30),
    "Phone" character varying(20),
    "WhatsApp" character varying(20),
    "Email" character varying(150),
    "Website" character varying(200),
    "AddressId" integer,
    "LogoFileName" character varying(255),
    "LogoContentType" character varying(100),
    "LogoStoragePath" character varying(500),
    "LogoData" bytea,
    "FooterMessage" character varying(500),
    "AdditionalInformation" character varying(1000),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_WorkshopSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkshopSettings_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL
);


CREATE TABLE "RolePermissions" (
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Username" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastLoginAt" timestamp without time zone,
    "RoleId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Bicycles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "Brand" character varying(80) NOT NULL,
    "Model" character varying(80) NOT NULL,
    "Color" character varying(50),
    "FrameSize" character varying(30),
    "SerialNumber" character varying(100),
    "BikeType" integer NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Bicycles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bicycles_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sku" character varying(50) NOT NULL,
    "Barcode" character varying(50),
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "ProductCategoryId" integer NOT NULL,
    "SupplierId" integer,
    "CostPrice" numeric(18,2) NOT NULL,
    "SalePrice" numeric(18,2) NOT NULL,
    "StockQuantity" numeric(18,2) NOT NULL,
    "MinimumStock" numeric(18,2) NOT NULL,
    "Unit" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "RowVersion" bytea NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_ProductCategories_ProductCategoryId" FOREIGN KEY ("ProductCategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL
);


CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "EntityName" character varying(100) NOT NULL,
    "EntityId" character varying(50) NOT NULL,
    "Action" character varying(50) NOT NULL,
    "OldValues" text,
    "NewValues" text,
    "IpAddress" character varying(50),
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE "UserRefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp without time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_UserRefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "WorkOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Number" character varying(30) NOT NULL,
    "CustomerId" integer NOT NULL,
    "BicycleId" integer NOT NULL,
    "OpeningDate" timestamp without time zone NOT NULL,
    "ExpectedDate" timestamp without time zone,
    "CompletionDate" timestamp without time zone,
    "Status" integer NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CustomerComplaint" text,
    "TechnicalEvaluation" text,
    "TechnicalNotes" text,
    "Discount" numeric(18,2) NOT NULL,
    "AdditionalCharge" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "RequestedTotal" numeric(18,2),
    "ApprovedTotal" numeric(18,2),
    "ApprovalStatus" integer NOT NULL,
    "ApprovalDate" timestamp without time zone,
    "ApprovedByUserId" integer,
    "ApprovalNotes" text,
    "AssignedToUserId" integer,
    "CreatedByUserFkId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_WorkOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkOrders_Bicycles_BicycleId" FOREIGN KEY ("BicycleId") REFERENCES "Bicycles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkOrders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkOrders_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_WorkOrders_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_WorkOrders_Users_CreatedByUserFkId" FOREIGN KEY ("CreatedByUserFkId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE "StockMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "Type" integer NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "PreviousStock" numeric(18,2) NOT NULL,
    "NewStock" numeric(18,2) NOT NULL,
    "UnitCost" numeric(18,2) NOT NULL,
    "ReferenceType" text,
    "ReferenceId" integer,
    "Description" text,
    "CreatedByUserId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_StockMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockMovements_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StockMovements_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE "Sales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Number" character varying(30) NOT NULL,
    "CustomerId" integer NOT NULL,
    "WorkOrderId" integer,
    "SaleDate" timestamp without time zone NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    "Discount" numeric(18,2) NOT NULL,
    "AdditionalCharge" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "CancelledByUserId" integer,
    "CancelledAt" timestamp without time zone,
    "CancellationReason" text,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "CreatedByUserId" integer,
    "UpdatedByUserId" integer,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sales_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Sales_Users_CancelledByUserId" FOREIGN KEY ("CancelledByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Sales_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Sales_WorkOrders_WorkOrderId" FOREIGN KEY ("WorkOrderId") REFERENCES "WorkOrders" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "WorkOrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkOrderId" integer NOT NULL,
    "ItemType" integer NOT NULL,
    "ProductId" integer,
    "ServiceId" integer,
    "Description" character varying(200) NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Discount" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_WorkOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkOrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkOrderItems_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkOrderItems_WorkOrders_WorkOrderId" FOREIGN KEY ("WorkOrderId") REFERENCES "WorkOrders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "WorkOrderStatusHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkOrderId" integer NOT NULL,
    "PreviousStatus" integer NOT NULL,
    "NewStatus" integer NOT NULL,
    "Reason" character varying(300),
    "ChangedByUserId" integer,
    "ChangedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_WorkOrderStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkOrderStatusHistories_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_WorkOrderStatusHistories_WorkOrders_WorkOrderId" FOREIGN KEY ("WorkOrderId") REFERENCES "WorkOrders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "SaleItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SaleId" integer NOT NULL,
    "ItemType" integer NOT NULL,
    "ProductId" integer,
    "ServiceId" integer,
    "Description" character varying(200) NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Discount" numeric(18,2) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaleItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SaleItems_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "SalePayments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SaleId" integer NOT NULL,
    "PaymentMethodId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Installments" integer NOT NULL,
    "TransactionCode" character varying(100),
    "PaidAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_SalePayments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SalePayments_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SalePayments_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");


CREATE INDEX "IX_AuditLogs_EntityName" ON "AuditLogs" ("EntityName");


CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");


CREATE INDEX "IX_Bicycles_CustomerId" ON "Bicycles" ("CustomerId");


CREATE INDEX "IX_Bicycles_SerialNumber" ON "Bicycles" ("SerialNumber");


CREATE INDEX "IX_Customers_AddressId" ON "Customers" ("AddressId");


CREATE UNIQUE INDEX "IX_Customers_CpfCnpj" ON "Customers" ("CpfCnpj") WHERE "CpfCnpj" IS NOT NULL;


CREATE INDEX "IX_Customers_Name" ON "Customers" ("Name");


CREATE UNIQUE INDEX "IX_PaymentMethods_Code" ON "PaymentMethods" ("Code");


CREATE UNIQUE INDEX "IX_Permissions_Code" ON "Permissions" ("Code");


CREATE UNIQUE INDEX "IX_ProductCategories_Name" ON "ProductCategories" ("Name");


CREATE UNIQUE INDEX "IX_Products_Barcode" ON "Products" ("Barcode") WHERE "Barcode" IS NOT NULL;


CREATE INDEX "IX_Products_Name" ON "Products" ("Name");


CREATE INDEX "IX_Products_ProductCategoryId" ON "Products" ("ProductCategoryId");


CREATE UNIQUE INDEX "IX_Products_Sku" ON "Products" ("Sku");


CREATE INDEX "IX_Products_SupplierId" ON "Products" ("SupplierId");


CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");


CREATE INDEX "IX_SaleItems_ProductId" ON "SaleItems" ("ProductId");


CREATE INDEX "IX_SaleItems_SaleId" ON "SaleItems" ("SaleId");


CREATE INDEX "IX_SaleItems_ServiceId" ON "SaleItems" ("ServiceId");


CREATE INDEX "IX_SalePayments_PaymentMethodId" ON "SalePayments" ("PaymentMethodId");


CREATE INDEX "IX_SalePayments_SaleId" ON "SalePayments" ("SaleId");


CREATE INDEX "IX_Sales_CancelledByUserId" ON "Sales" ("CancelledByUserId");


CREATE INDEX "IX_Sales_CreatedByUserId" ON "Sales" ("CreatedByUserId");


CREATE INDEX "IX_Sales_CustomerId" ON "Sales" ("CustomerId");


CREATE UNIQUE INDEX "IX_Sales_Number" ON "Sales" ("Number");


CREATE INDEX "IX_Sales_SaleDate" ON "Sales" ("SaleDate");


CREATE INDEX "IX_Sales_Status" ON "Sales" ("Status");


CREATE UNIQUE INDEX "IX_Sales_WorkOrderId" ON "Sales" ("WorkOrderId");


CREATE INDEX "IX_StockMovements_CreatedAt" ON "StockMovements" ("CreatedAt");


CREATE INDEX "IX_StockMovements_CreatedByUserId" ON "StockMovements" ("CreatedByUserId");


CREATE INDEX "IX_StockMovements_ProductId" ON "StockMovements" ("ProductId");


CREATE INDEX "IX_Suppliers_AddressId" ON "Suppliers" ("AddressId");


CREATE UNIQUE INDEX "IX_Suppliers_CpfCnpj" ON "Suppliers" ("CpfCnpj") WHERE "CpfCnpj" IS NOT NULL;


CREATE INDEX "IX_UserRefreshTokens_UserId" ON "UserRefreshTokens" ("UserId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");


CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");


CREATE INDEX "IX_WorkOrderItems_ProductId" ON "WorkOrderItems" ("ProductId");


CREATE INDEX "IX_WorkOrderItems_ServiceId" ON "WorkOrderItems" ("ServiceId");


CREATE INDEX "IX_WorkOrderItems_WorkOrderId" ON "WorkOrderItems" ("WorkOrderId");


CREATE INDEX "IX_WorkOrders_ApprovedByUserId" ON "WorkOrders" ("ApprovedByUserId");


CREATE INDEX "IX_WorkOrders_AssignedToUserId" ON "WorkOrders" ("AssignedToUserId");


CREATE INDEX "IX_WorkOrders_BicycleId" ON "WorkOrders" ("BicycleId");


CREATE INDEX "IX_WorkOrders_CreatedByUserFkId" ON "WorkOrders" ("CreatedByUserFkId");


CREATE INDEX "IX_WorkOrders_CustomerId" ON "WorkOrders" ("CustomerId");


CREATE UNIQUE INDEX "IX_WorkOrders_Number" ON "WorkOrders" ("Number");


CREATE INDEX "IX_WorkOrders_OpeningDate" ON "WorkOrders" ("OpeningDate");


CREATE INDEX "IX_WorkOrders_Status" ON "WorkOrders" ("Status");


CREATE INDEX "IX_WorkOrderStatusHistories_ChangedByUserId" ON "WorkOrderStatusHistories" ("ChangedByUserId");


CREATE INDEX "IX_WorkOrderStatusHistories_WorkOrderId" ON "WorkOrderStatusHistories" ("WorkOrderId");


CREATE INDEX "IX_WorkshopSettings_AddressId" ON "WorkshopSettings" ("AddressId");


CREATE INDEX "IX_WorkshopSettings_IsActive" ON "WorkshopSettings" ("IsActive");


